### ISSUE TITLE
Configure iD to use historical tile servers in addition to current Bing imagery

### ISSUE THREAD

**Issue by jeffmeyer** [OpenHistoricalMap/ohm-website#10]

**Comment by Abbe98** [comment]
More historical tile sources can be found [here](https://github.com/osmlab/historic-imagery-index/blob/gh-pages/imagery.json), but don't know if any of them are interesting... 

Also see [here](https://github.com/OpenHistoricalMap/iD/commit/54fdbd3f880d174a8fe8ceda21aa09a748d0b876).
