### ISSUE TITLE
Add Racetrack support

### ISSUE THREAD

**Issue by jeffreyameyer** [OpenHistoricalMap/ohm-website#2]
it would be nice for my purposes if highway=raceway were rendered, as that’s the whole purpose of Ghost Tracks. it would be meaningful here because Empire Raceways is right next door to the Menand Drive In and would show on the time slider as appearing and disappearing about the same times. also, being a drive in theater, rendering of the parking area would be nice.

Richard Welty  11 minutes ago
go to this link, and switch the base layer (upper right) to OHM to see what i get from the OHM tile server now: http://www.na-motorsports.com/Tracks/NY/Menands.html#TrackMap

@rwelty1889

**Comment by danrademacher** [comment]
these are rendered:
![image](https://user-images.githubusercontent.com/1423200/120870811-c816f200-c54e-11eb-9441-e621e0f6a328.png)
