### ISSUE TITLE
custom version of iD needs new help text contributed 

### ISSUE THREAD

**Issue by metazool** [OpenHistoricalMap/ohm-website#20]
" the help section that has to be rewritten for OHM. Adding a section about how to use tools like Maps Warper/Fieldmaps and a section about the legal aspects of the project"

**Comment by Abbe98** [comment]
Also: [OpenHistoricalMap/iD/#2](https://github.com/OpenHistoricalMap/iD/issues)

**Comment by Abbe98** [comment]
New help section now live at http://openhistoricalmap.github.io/iD/id/ .

Still need to be improved.

**Comment by rwarren2** [comment]
Merged to #38
