### ISSUE TITLE
Reset/Update The Rails Port

### ISSUE THREAD

**Issue by Abbe98** [OpenHistoricalMap/ohm-website#21]
Google is killing the existing login system in less than two weeks and the OpenStreetMap Rails Port is 475 commits ahead of this fork.

When OpenStreetMap updates the main site(probably prior to Apirl 20) we should do the same.

It [doesn't seams to be](https://github.com/OpenHistoricalMap/ohm-website/commits/master) any major differences from the old OSM site and the update should be done quite fast.

I'm going to work on this as soon as [openstreetmap#918](https://github.com/openstreetmap/openstreetmap-website/pull/918) is live and stable.

The aim is also to get the new instance of iD compiled in the same wave!

Would get the license/terms issue solved too([related](https://github.com/OpenHistoricalMap/ohm-website/commit/293f7c7515b30fed76d0dee72c38e17d61670738)).

**Comment by Abbe98** [comment]
Not 100% sure on what that needs to be done at database level(changeset comments?)...

**Comment by pnorman** [comment]
the migrations should handle that - but not sure how to run them.

**Comment by rwarren2** [comment]
Move to #38
