### ISSUE TITLE
Whilst trying to sign up for OHM I was asked to contact webmaster@openstreetmap.org

### ISSUE THREAD

**Issue by SomeoneElseOSM** [OpenHistoricalMap/ohm-website#24]
I'm guessing that might be from in here:

https://github.com/OpenHistoricalMap/ohm-website/blob/master/app/views/user/suspended.html.erb

**Comment by Abbe98** [comment]
Yes this is a known issue. 

We are having a major update of the site upcoming.

**Comment by rwarren2** [comment]
Resolved. +2 years. :/
