### ISSUE TITLE
openhistoricalmap.org offline

### ISSUE THREAD

**Issue by harry-wood** [OpenHistoricalMap/ohm-website#25]
http://www.openhistoricalmap.org is currently offline for some reason

**Comment by Abbe98** [comment]
Been so for for a few months

**Comment by rwarren2** [comment]
I've sent the mail to track down who has root access. The machine is now reporting a new ssh key. :(

**Comment by timwaters** [comment]
Machine is still offline - situation is still as described on ohm mailing list (where further discussion about this issue should be ideally placed for more visibility)  Machine probably wont come back online as it is but if someone wants to take ownership via a transfer they can fix it up. Current status is we've backed everything up and waiting for people with time and knowledge to resurrect the various components.

**Comment by harry-wood** [comment]
The ['historic' mailing list](https://lists.openstreetmap.org/pipermail/historic/2016-August/thread.html#1005) you mean. ok I'll close this so that discussion stays there

**Comment by rwarren2** [comment]
Building new hosting machine as fast as possible.
