### ISSUE TITLE
Move filesystems over to XFS for speed + reliability.

### ISSUE THREAD

**Issue by rwarren2** [OpenHistoricalMap/ohm-website#27]
There will be some downtime for this.

**Comment by rwarren2** [comment]
cache folder needs cleanup immediately.

**Comment by rwarren2** [comment]
Machine to go offline for about 2 mins circa 2PM EST for drive changeover.

**Comment by rwarren2** [comment]
Make that 12 hours to copy over main raid array.

**Comment by rwarren2** [comment]
Back online. One last filesystem to move. Should not impact operations.

**Comment by rwarren2** [comment]
Will take system down for a few hours at 11PM for one last disk change over. Current migration is making OHM performance unacceptable.

**Comment by rwarren2** [comment]
Outage still into it's second day. No data loss so far.

**Comment by rwarren2** [comment]
Machine filesystems back online.
dump.openhistoricalmap.org back online and well as rsync deamon.

**Comment by todrobbins** [comment]
Great work @rwarren2!

**Comment by rwarren2** [comment]
Tile server installed.

**Comment by rwarren2** [comment]
Server being upgraded to Ubuntu 16.04.4 LTS because of insane JDK 8 and gcc requirements for OSM tools.

**Comment by rwarren2** [comment]
tile server is up.
tiles are _not_ being updated.
HOSM is up.
Dumps are _not_ being done.
By the Minute are _not_ being done.
XAPI is _not_ up.
SPARQL is _not_ up.

**Comment by rwarren2** [comment]
tile server is up.
tiles are being updated (with bugs)
HOSM is up.
Dumps are being done.
By the Minute and by Day are being done.
XAPI is up.
