### ISSUE TITLE
Set maxzoom on OHM layer to 19 for AWS staging site

### ISSUE THREAD

**Issue by danrademacher** [OpenHistoricalMap/ohm-website#45]
I imagined there would be an easy change somewhere around here:
https://github.com/OpenHistoricalMap/ohm-website/blob/ohm-mapbox-gl/vendor/assets/leaflet/leaflet.osm.js#L26

to make that 19 since we're not rendering tiles above 19 at the moment. But that's referencing the raster tile endpoint  and the GL layer seems to have no specified upper limit at all. like you can click your way to this:
http://openhistoricalmap-1936150974.us-east-1.elb.amazonaws.com/#map=31/47.60340/-122.33465&layers=O

Dumb question: Where do we actually specify the max zoom for a GL layer?

@jimmyrocks do you have any time to respond? I suspect the answer is very easy and I've just spent too many years flying at PM level in Leaflet-land....

**Comment by jimmyrocks** [comment]
I am traveling today, so I can look into this more later. But I think I can help a little now.

The code that controls the layers can be found here:
https://github.com/OpenHistoricalMap/ohm-website/blob/ohm-mapbox-gl/app/assets/javascripts/ohm.style.js#L66

After looking through the mapbox documentation, I'm not sure if maxzoom will work on vector layers. We may have to adjust the layer settings when the vector tiles are creates. I would first try adding it to the layer to see if it works, after that I would look at anything else that can be done in the style or in the tile generation itself.

**Comment by danrademacher** [comment]
We're taking a look to see if this is something we can change in Tessera configs over at https://github.com/OpenHistoricalMap/openhistoricaltiles

**Comment by gregallensworth** [comment]
This was a simple tessera setting: `maxzoom: 22`

Lesson learned: The OpenMapTiles wrapper `layer_XXX()` functions e.g. `layer_water(bbox, z)` use `>=` operator for the zoom level. Example: `layer_waterway(bbox geometry, zoom_level int)` uses `SELECT * FROM waterway_z14 WHERE zoom_level >= 14` so a zoom of 15, 18, 20, 22, or whatever would use that same view.

Therefore, increasing this Tessera setting _did not_ require going back into OMT's scripts to create more views.

**Comment by danrademacher** [comment]
Super. And confirmed working on the live AWs site
