### ISSUE TITLE
redirect from http to https for openhistoricalmap.org

### ISSUE THREAD

**Issue by jeffreyameyer** [OpenHistoricalMap/ohm-website#48]
Apparently, there are still some non-https switching / preferring browsers and users out there.

Not urgent.

**Comment by jeffreyameyer** [comment]
![image](https://user-images.githubusercontent.com/1494546/67603656-5f3e8580-f72e-11e9-83c8-f58c7588c2db.png)

**Comment by rwarren2** [comment]
Bad browsers.. The website is at www.openhistoricalmap.org. I'll get rid of the other entry since it causes confusion.
