### ISSUE TITLE
Welcome page text innacurate

### ISSUE THREAD

**Issue by InsertUser** [OpenHistoricalMap/ohm-website#7]
The [Welcome page](https://www.openhistoricalmap.org/welcome) for new mappers has the same text as that for the main openstreetmap page including the warning that:

"What it doesn't include is opinionated data like ratings, historical or hypothetical feature"

The warning against historical features in particular seems somewhat counterproductive in OHM.

**Comment by jeffreyameyer** [comment]
Yep! We're actually in the process of fixing that right now... it should be in staging.

We'll confirm once it's live in production.
